apiVersion: v1
kind: Service
metadata:
  name: identity-service-banking-ekyc
  namespace: default
spec:
  selector:
    app: identity-service-banking-ekyc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
